---
title: "Simulations"
author: "Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# Simulations

```{r }
rpois(n=1000, 100)
 

x=rpois(n=1000, lambda =100)
hist(x)

mean(x)
var(x)
#x=rpois(n=10, lambda = c(50,100)) if we want to have 2 different values for lambda, then recycle the values

z=rnbinom(n=10000,mu = 100, size = 1) #mu is the mean of distribution and the variance is mu+mu^2/size 
mean(z)
var(z)

```

# Analyses
## Test for differences between samples
```{r }
data=data.frame(sample=rep(c("sample_1","sample_2")), count=rpois(n=1000, lambda = c(10,100)))
head(data)

tapply(data$count, data$sample, mean)

#ANOVA
m0 <- aov(log(count+1)~1, data = data)
summary(m0)

m1 <- aov(log(count+1)~sample, data = data)
summary(m1)

anova(m1)

anova(m0, m1, test="F")

#Linear model
m0 <- lm(log(count+1)~1, data = data)
summary(m0)

m1 <- lm(log(count+1)~sample, data = data)
summary(m1)

anova(m1)
anova(m0, m1, test="F")

# GLM
m0 <- glm(count~1, data = data, family="poisson")
summary(m0)
-2*logLik(m0)

m1 <- glm(count~sample, data = data, family="poisson")
summary(m1)
-2*logLik(m1)
-2*logLik(m0)+2*logLik(m1)

anova(m1, test="Chisq")
anova(m0, m1, test="Chisq")
```
## Compute repeatability
```{r }
data <- sample_Poisson(sample=c("sample_1","sample_2"), count=10, lambda= c(10,100))
#Linear model
m0 <- lme4::lmer(log(count+1)~1+(1|sample), data = data)
summary(m0)

## Extract variance components
varcomp <- data.frame(lme4::VarCorr(m0))$vcov

## Compute repeatability
repeatability = varcomp[1]/sum(varcomp)
repeatability


```

# Sample abundance table
## Only two OTUs (binomial sampling)
```{r}

sample_Binomial(Nhabitats=10, prob=0.5, mean_nindiviuals_per_habitat=5)
```

## More than two OTUs (multinomial sampling)
### Sample abundance table
```{r}
nOTU=3
Nhabitats=10
## Sample OTU abundance data
otu_mat <- sample_Multinomial(Nhabitats=Nhabitats, prob=c(0.1, 0.1, 0.8), mean_nindiviuals_per_habitat=10)

## Please add the missing columns here with fake names for Division, Class, ..., Genus
## Create table with taxonomy
tax_mat <- data.frame(otu=paste0("OTU", 1:nOTU), Domain=rep("Eukaryota", nOTU), Supergroup=paste0("Supergroup", 1:nOTU))

## create metadata
samples_df <- data.frame(sample=paste0("sample_", 1:Nhabitats), TypeofHabitat=as.character(sample(c("Type1", "Type2"), Nhabitats, replace = TRUE)), Temperature=as.character(sample(c(17, 20), Nhabitats, replace = TRUE)))

## Check number of the two habitats
table(samples_df$TypeofHabitat)

## Please follow the instructions here to prepare your data (without subsetting samples or taxa): https://vaulot.github.io/tutorials/Phyloseq_tutorial.html#read-the-data-and-create-phyloseq-objects

```


### Rarefaction curves
```{r, eval=FALSE}

## Prepare plot
p <- phyloseq.extended::ggrare(yourphyloseqobject,
            step = 2,
            color = "TypeofHabitat",
            plot = TRUE,
            parallel = TRUE,
            se = FALSE)

## Define a minimum sample size for rarefaction curve
minSampSize<- min(sample_sums(yourphyloseqobject))

## Split plot by type of habitat
p <- p + 
  facet_wrap(~ TypeofHabitat ) + 
  geom_vline(xintercept = minSampSize, color = "gray60")
p
```

### Plot abundance and alpha diversity by sample
```{r}
## use the code available here: https://vaulot.github.io/tutorials/Phyloseq_tutorial.html#bar-graphs)
         
```
### Beta diversity
```{r, eval=FALSE}
  dist.a <- distance(yourphyloseqobject, method = "bray")
  pa <- phyloseq.extended::plot_dist_as_heatmap(dist.a, title = "Heatmap plot of the beta distance (Bray Curtis) 
between each pair of samples") + 
    theme(plot.title = element_text(hjust = 0.5))
  pa
  
```

# Usefull links
https://southgreenplatform.github.io/trainings/linux/metabarcodingPractice/#rarefaction
https://vaulot.github.io/tutorials/Phyloseq_tutorial.html
http://joey711.github.io/waste-not-supplemental/minimal-rarefy-example/minimal-rarefy-example.html
