---
title: "Repeatability_16S"
author: "David Gerin-Jean, Chloé Perrais"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```

## Compute repeatability using LMM
```{r }
#importe data
data16S <- data.table::fread(file=file.path(here::here(), "data", "derived_data", "2022_16S_JRLAT_cleaned_filtered_abundance_final.tsv"),sep="\t",header=TRUE)

#split to have family names
data16S_family <- tidyr::separate(data=data16S, col=blast_taxonomy, into=c("kingdom","phylum","class","order","family","genus","species"),  sep=";")
```

#Acetobacter
```{r }
#group the family
dataAAB <- subset(data16S_family, family=="Acetobacteraceae")
#remove useless column
dataAAB_final <- dataAAB[,19:306]
#sum of each row for 1 column
dataAAB_sum_final <- data.frame("count"=Matrix::colSums(dataAAB_final))

library(tidyverse)
dataAAB_sum_final <- dataAAB_sum_final%>%
  rownames_to_column(var="Sample")

dataAAB_sum_final$Sample=gsub("A","",dataAAB_sum_final$Sample)
dataAAB_sum_final$Sample=gsub("B","",dataAAB_sum_final$Sample)
dataAAB_sum_final$Sample=gsub("C","",dataAAB_sum_final$Sample)

#Linear model
m0 <- lme4::lmer(log(count+1)~1+(1|Sample), data = dataAAB_sum_final)
summary(m0)
## Extract variance components
varcomp <- data.frame(lme4::VarCorr(m0))$vcov
## Compute repeatability
repeatability = varcomp[1]/sum(varcomp)
repeatability
```
 
#Lactobacillaceae
```{r }
#group the family
dataLAB <- subset(data16S_family, family=="Lactobacillaceae")
#remove useless column
dataLAB_final <- dataLAB[,19:306]
#sum of each row for 1 column
dataLAB_sum_final <- data.frame("count"=Matrix::colSums(dataLAB_final))

library(tidyverse)
dataLAB_sum_final <- dataLAB_sum_final%>%
  rownames_to_column(var="Sample")

dataLAB_sum_final$Sample=gsub("A","",dataLAB_sum_final$Sample)
dataLAB_sum_final$Sample=gsub("B","",dataLAB_sum_final$Sample)
dataLAB_sum_final$Sample=gsub("C","",dataLAB_sum_final$Sample)

#Linear model
m0 <- lme4::lmer(log(count+1)~1+(1|Sample), data = dataLAB_sum_final)
summary(m0)
## Extract variance components
varcomp <- data.frame(lme4::VarCorr(m0))$vcov
## Compute repeatability
repeatability = varcomp[1]/sum(varcomp)
repeatability
```
 
 
#Enterobacteriaceae
```{r }
#group the family
dataENT <- subset(data16S_family, family=="Enterobacteriaceae")
#remove useless column
dataENT_final <- dataENT[,19:306]
#sum of each row for 1 column
dataENT_sum_final <- data.frame("count"=Matrix::colSums(dataENT_final))

library(tidyverse)
dataENT_sum_final <- dataENT_sum_final%>%
  rownames_to_column(var="Sample")

dataENT_sum_final$Sample=gsub("A","",dataENT_sum_final$Sample)
dataENT_sum_final$Sample=gsub("B","",dataENT_sum_final$Sample)
dataENT_sum_final$Sample=gsub("C","",dataENT_sum_final$Sample)

#Linear model
m0 <- lme4::lmer(log(count+1)~1+(1|Sample), data = dataENT_sum_final)
summary(m0)
## Extract variance components
varcomp <- data.frame(lme4::VarCorr(m0))$vcov
## Compute repeatability
repeatability = varcomp[1]/sum(varcomp)
repeatability


##if we use only the positive sample

#group the family
dataENTp <- subset(data16S_family, family=="Enterobacteriaceae")
#remove useless column
dataENTp_final <- dataENTp[,19:306]
#sum of each row for 1 column
dataENTp_sum_final <- data.frame("count"=Matrix::colSums(dataENTp_final))

library(tidyverse)
dataENTp_sum_final <- dataENTp_sum_final%>%
  rownames_to_column(var="Sample")

dataENTp_sum_final$Sample=gsub("A","",dataENTp_sum_final$Sample)
dataENTp_sum_final$Sample=gsub("B","",dataENTp_sum_final$Sample)
dataENTp_sum_final$Sample=gsub("C","",dataENTp_sum_final$Sample)

#select only count>1
dataENTp_sum_final=subset(dataENTp_sum_final, count>1)

#Linear model
m0 <- lme4::lmer(log(count+1)~1+(1|Sample), data = dataENTp_sum_final)
summary(m0)
## Extract variance components
varcomp <- data.frame(lme4::VarCorr(m0))$vcov
## Compute repeatability
repeatability = varcomp[1]/sum(varcomp)
repeatability
```

#Anaplasmataceae
```{r }
#group the family
dataWOL <- subset(data16S_family, family=="Anaplasmataceae")
#remove useless column
dataWOL_final <- dataWOL[,19:306]
#sum of each row for 1 column
dataWOL_sum_final <- data.frame("count"=Matrix::colSums(dataWOL_final))

library(tidyverse)
dataWOL_sum_final <- dataWOL_sum_final%>%
  rownames_to_column(var="Sample")

dataWOL_sum_final$Sample=gsub("A","",dataWOL_sum_final$Sample)
dataWOL_sum_final$Sample=gsub("B","",dataWOL_sum_final$Sample)
dataWOL_sum_final$Sample=gsub("C","",dataWOL_sum_final$Sample)

#Linear model
m0 <- lme4::lmer(log(count+1)~1+(1|Sample), data = dataWOL_sum_final)
summary(m0)
## Extract variance components
varcomp <- data.frame(lme4::VarCorr(m0))$vcov
## Compute repeatability
repeatability = varcomp[1]/sum(varcomp)
repeatability
```
